### ISSUE TITLE
raw10 to jpg tool

### ISSUE THREAD

**Issue by Ninic0c0** [ArduCAM/MIPI_Camera#19]
Hello,

Could you please provide some assistance to use your code :)

I just want  to load our data-set (raw10) from python3/opencv2 but your tool seems bogus....

Cheers,

```
pi@raspberrypi:~/MIPI_Camera/RPI/python $ python3 capture_raw.py 
Open camera...
Found sensor ov9281 at address 60
Setting the resolution...
Can't open the file
mmal: Failed to fix lens shading, use the default mode!
Current resolution is (640, 400)
Reset the focus...
reset_control: Unexpected result.
The camera may not support this control.
Enable Auto Exposure...
Enable Auto White Balance...
software_auto_white_balance: Unexpected result.
Close camera...
pi@raspberrypi:~/MIPI_Camera/RPI/python $ cd ../utils/
pi@raspberrypi:~/MIPI_Camera/RPI/utils $ python3 mipi_raw10_to_jpg.py ../python/640x400.raw 640x400.jpg 640 400 gray
Notice:This program only support csi-2 raw 10bit packet data convert to jpg.

Traceback (most recent call last):
  File "mipi_raw10_to_jpg.py", line 74, in <module>
    img = unpack_mipi_raw10(remove_padding(data, width, height, 10)).reshape(height, width, 1)
  File "mipi_raw10_to_jpg.py", line 48, in remove_padding
    buff = buff.reshape(align_height, align_width)
ValueError: cannot reshape array of size 256000 into shape (400,800)

```

**Comment by ArduCAM** [comment]
We now moved our support to our forum, please resent the questions to https://www.arducam.com/forums/ 
Thank you.
